//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCMeldenChatbericht.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public string Reason { get; set; }
        public string message_Id { get; set; }
        public string Reported_User_Id { get; set; }
        public string Type { get; set; }
        public string user_Id { get; set; }
    }
}
