//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCMeldenChatbericht
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public string Chatmessage { get; set; }
        public string ChatmessageSender { get; set; }
        public string Reason { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
